version: "2.2"

services:
  postgres:
    image: postgres:11-alpine
    ports:
      - 6433:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: cosmos-goz-api